"""
Central catalog of 100 Professional Hindi Voice Profiles.

Every voice profile is a legitimate, technically distinct configuration
with concrete acoustic parameters:
- Unique ID and Hindi persona name
- Gender (male / female)
- Production category (news, storytelling, commercial, educational, etc.)
- Acoustic style (deep, authoritative, warm, energetic, calm, etc.)
- Engine conditioning prompt (for Indic Parler-TTS / prompt-conditioned engines)
- Prosody tuning (base speaker, pitch offset, rate multiplier, contour)
- Search tags and Hindi sample preview text
"""
from __future__ import annotations

from typing import Any, TypedDict


class HindiVoiceProfile(TypedDict):
    id: str
    name: str
    gender: str  # "male" | "female"
    category: str
    style: str
    description: str
    engine: str
    base_speaker: str
    prompt: str
    pitch: str
    rate: float
    tags: list[str]
    preview_text: str


HINDI_VOICES: list[HindiVoiceProfile] = [
    # =========================================================================
    # 1. NEWS & BROADCAST (1-8)
    # =========================================================================
    {
        "id": "hi-male-news-anchor-01",
        "name": "Rohit — Prime Time News",
        "gender": "male",
        "category": "News & Broadcast",
        "style": "Authoritative & Crisp",
        "description": "Clear, commanding prime-time news anchor voice with precise Hindi diction and formal cadence.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A professional male news anchor speaking formal Hindi with crisp pronunciation, authoritative tone, and clear studio acoustics.",
        "pitch": "-5%",
        "rate": 1.02,
        "tags": ["news", "anchor", "breaking", "formal", "prime time"],
        "preview_text": "नमस्कार, आज के मुख्य समाचारों के साथ मैं रोहित। देश और दुनिया की तमाम बड़ी ख़बरों पर एक नज़र।",
    },
    {
        "id": "hi-female-news-anchor-02",
        "name": "Kavita — National Bulletin",
        "gender": "female",
        "category": "News & Broadcast",
        "style": "Formal & Confident",
        "description": "Polished national news anchor voice with sharp articulation, balanced pitch, and steady pacing.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A female newsreader speaking formal Hindi in a confident, clear, and neutral tone with studio quality audio.",
        "pitch": "+0%",
        "rate": 1.0,
        "tags": ["news", "national", "bulletin", "female", "formal"],
        "preview_text": "दिनभर की बड़ी ख़बरों के विशेष बुलेटिन में आपका स्वागत है। आइए सीधे चलते हैं मुख्य समाचारों की ओर।",
    },
    {
        "id": "hi-male-breaking-news-03",
        "name": "Vikram — Breaking News",
        "gender": "male",
        "category": "News & Broadcast",
        "style": "Urgent & High Impact",
        "description": "Dynamic, fast-paced reporting voice crafted for breaking alerts and live updates.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An energetic male reporter delivering breaking news in Hindi with urgency, fast pace, and clear vocal projection.",
        "pitch": "+3%",
        "rate": 1.10,
        "tags": ["news", "breaking", "urgent", "fast", "live"],
        "preview_text": "इस वक़्त की बड़ी ख़बर सामने आ रही है। सूत्रों के मुताबिक महत्वपूर्ण फ़ैसला कुछ ही मिनटों में लिया जा सकता है।",
    },
    {
        "id": "hi-female-field-reporter-04",
        "name": "Pooja — Field Reporter",
        "gender": "female",
        "category": "News & Broadcast",
        "style": "Active & Engaging",
        "description": "On-ground reporter voice with realistic cadence and spontaneous journalistic energy.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A female field journalist reporting in conversational yet professional Hindi with natural outdoor cadence.",
        "pitch": "+4%",
        "rate": 1.05,
        "tags": ["news", "ground report", "journalist", "reporter"],
        "preview_text": "हम सीधे ग्राउंड ज़ीरो से लाइव जुड़े हैं। यहाँ लोगों की भारी भीड़ जमा है और माहौल बेहद गर्म है।",
    },
    {
        "id": "hi-male-editorial-05",
        "name": "Deepak — Editorial Analysis",
        "gender": "male",
        "category": "News & Broadcast",
        "style": "Thoughtful & Measured",
        "description": "Deep, reflective tone for in-depth policy debates, opinion columns, and political analysis.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A senior male journalist delivering an analytical Hindi editorial in a calm, intellectual, and deliberate manner.",
        "pitch": "-8%",
        "rate": 0.95,
        "tags": ["news", "editorial", "analysis", "politics", "deep"],
        "preview_text": "इस नीतिगत फ़ैसले के दूरगामी आर्थिक प्रभाव क्या होंगे, आइए इस पर एक विश्लेषणात्मक दृष्टि डालते हैं।",
    },
    {
        "id": "hi-female-financial-news-06",
        "name": "Smita — Market & Business",
        "gender": "female",
        "category": "News & Broadcast",
        "style": "Sharp & Professional",
        "description": "Quick, precise diction ideal for stock market updates, mutual funds, and business rundowns.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A female business news anchor speaking Hindi rapidly and crisply about financial markets and economic indices.",
        "pitch": "+2%",
        "rate": 1.04,
        "tags": ["business", "finance", "markets", "stocks", "economy"],
        "preview_text": "शेयर बाज़ार में आज शानदार तेज़ी देखने को मिली है। सेंसेक्स और निफ़्टी दोनों रिकॉर्ड स्तर पर बंद हुए हैं।",
    },
    {
        "id": "hi-male-sports-desk-07",
        "name": "Rajat — Sports News Desk",
        "gender": "male",
        "category": "News & Broadcast",
        "style": "Energetic & Punchy",
        "description": "Punchy, passionate voice for sports recaps, cricket commentary, and match highlights.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An enthusiastic male sports anchor speaking Hindi with passion, strong accents on key words, and upbeat tempo.",
        "pitch": "+5%",
        "rate": 1.08,
        "tags": ["sports", "cricket", "match", "energetic"],
        "preview_text": "अंतिम गेंद पर रोमांचक जीत दर्ज करते हुए भारतीय टीम ने सिरीज़ पर अपना ऐतिहासिक कब्ज़ा जमा लिया है!",
    },
    {
        "id": "hi-female-weather-desk-08",
        "name": "Nisha — Weather & City",
        "gender": "female",
        "category": "News & Broadcast",
        "style": "Pleasant & Clear",
        "description": "Soothing, friendly broadcast voice for weather bulletins, city updates, and civic announcements.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A friendly female weather presenter speaking clear Hindi in a pleasant and informative tone.",
        "pitch": "+3%",
        "rate": 0.98,
        "tags": ["weather", "city", "pleasant", "daily update"],
        "preview_text": "उत्तर भारत में अगले तीन दिनों तक मौसम में भारी बदलाव के संकेत हैं। तापमान में गिरावट दर्ज की जाएगी।",
    },

    # =========================================================================
    # 2. STORYTELLING & KAHANIYAAN (9-18)
    # =========================================================================
    {
        "id": "hi-male-storyteller-classic-09",
        "name": "Kabir — Classic Katha Vachak",
        "gender": "male",
        "category": "Storytelling",
        "style": "Deep & Narrative",
        "description": "Rich, resonant Indian storyteller voice with natural pauses and dramatic tension for folktales.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A mature male storyteller with deep warm voice, speaking slow dramatic Hindi with expressive pauses.",
        "pitch": "-10%",
        "rate": 0.90,
        "tags": ["story", "katha", "classic", "folktale", "dramatic"],
        "preview_text": "एक समय की बात है, विंध्याचल की घनी वादियों के बीच बसा था एक रहस्यमयी गाँव, जहाँ रात होते ही सन्नाटा छा जाता था...",
    },
    {
        "id": "hi-female-dadi-kahani-10",
        "name": "Sharda — Dadi Ki Kahani",
        "gender": "female",
        "category": "Storytelling",
        "style": "Affectionate & Gentle",
        "description": "Maternal, loving elder voice evoking nostalgic bedtime stories and moral tales.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A kind and affectionate elderly female storyteller speaking gentle Hindi with warmth and bedtime rhythm.",
        "pitch": "-6%",
        "rate": 0.88,
        "tags": ["dadi", "bedtime", "children", "moral tales", "nostalgic"],
        "preview_text": "मेरे प्यारे बच्चों, आज मैं तुम्हें एक ऐसे दयालु राजकुमार की कहानी सुनाती हूँ जिसने पूरे जंगल के जीवों को बचाया।",
    },
    {
        "id": "hi-male-horror-mystery-11",
        "name": "Rudra — Horror & Mystery",
        "gender": "male",
        "category": "Storytelling",
        "style": "Dark & Suspenseful",
        "description": "Deep, haunting whisper-laced voice designed for ghost stories, crime thrillers, and dark mysteries.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A male horror narrator speaking in a low, ominous, slow Hindi voice with spine-chilling suspense.",
        "pitch": "-18%",
        "rate": 0.86,
        "tags": ["horror", "mystery", "crime", "dark", "suspense"],
        "preview_text": "उस पुरानी हवेली के बंद दरवाज़े के पीछे से... हर आधी रात को किसी के चलने की धीमी-धीमी आहट सुनाई देती थी...",
    },
    {
        "id": "hi-female-romantic-fiction-12",
        "name": "Meera — Romantic Fiction",
        "gender": "female",
        "category": "Storytelling",
        "style": "Soft & Expressive",
        "description": "Melodious, emotive female voice for modern romance novels, love stories, and poetry.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A soft-spoken female reading romantic fiction in Hindi with tender emotion and musical rhythm.",
        "pitch": "-2%",
        "rate": 0.92,
        "tags": ["romance", "fiction", "poetry", "emotional", "soft"],
        "preview_text": "उस शाम की ठंडी हवा में जब उसने पहली बार उसकी आँखों में देखा, तो मानो वक़्त की रफ़्तार वहीं थम सी गई थी।",
    },
    {
        "id": "hi-male-panchatantra-13",
        "name": "Aman — Panchatantra Tales",
        "gender": "male",
        "category": "Storytelling",
        "style": "Playful & Vibrant",
        "description": "Engaging, playful voice with animated character inflections for children's fables and animal stories.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A lively male narrator telling children's fables in Hindi with playful tone and expressive voice acting.",
        "pitch": "+6%",
        "rate": 1.02,
        "tags": ["panchatantra", "fables", "kids", "animals", "playful"],
        "preview_text": "एक चालाक लोमड़ी थी, जो हर रोज़ जंगल के सीधे-सादे जानवरों को अपनी मीठी-मीठी बातों से उल्लू बना देती थी!",
    },
    {
        "id": "hi-female-mythology-14",
        "name": "Gayatri — Puranic & Mythological",
        "gender": "female",
        "category": "Storytelling",
        "style": "Reverent & Grand",
        "description": "Noble, majestic narration crafted for Indian epics, Mahabharata, Ramayana, and temple legends.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A noble female narrator reciting mythological Hindi tales with grandeur, reverence, and dignified cadence.",
        "pitch": "+1%",
        "rate": 0.92,
        "tags": ["mythology", "epics", "mahabharata", "ramayana", "grand"],
        "preview_text": "कुरुक्षेत्र के उस विशाल धर्मक्षेत्र में जब दोनों सेनाएँ आमने-सामने खड़ी हुईं, तब गांडीवधारी अर्जुन के मन में संशय उठा।",
    },
    {
        "id": "hi-male-sci-fi-fantasy-15",
        "name": "Arya — Sci-Fi & Adventure",
        "gender": "male",
        "category": "Storytelling",
        "style": "Cinematic & Intense",
        "description": "Modern cinematic voice for space adventures, futuristic sci-fi tales, and high-stakes quests.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An intense male voice narrating science fiction in Hindi with cinematic weight and vivid imagination.",
        "pitch": "-6%",
        "rate": 0.98,
        "tags": ["scifi", "fantasy", "cinematic", "space", "adventure"],
        "preview_text": "साल 2085 में जब मानव जाति ने पहली बार सुदूर गैलेक्सी के उस सिग्नल को डिकोड किया, तो सब दंग रह गए।",
    },
    {
        "id": "hi-female-thriller-action-16",
        "name": "Tara — Thriller & Detective",
        "gender": "female",
        "category": "Storytelling",
        "style": "Gripping & Fast-Paced",
        "description": "Edge-of-the-seat female narrative voice for detective sleuths, police procedurals, and spy thrillers.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A fast and tense female voice narrating detective crime stories in Hindi with gripping suspense.",
        "pitch": "+1%",
        "rate": 1.05,
        "tags": ["detective", "crime", "thriller", "suspense", "fast"],
        "preview_text": "कमरे की बत्ती अचानक गुल हो गई। दरवाज़ा धीरे से खुला और इंस्पेक्टर को महसूस हुआ कि कातिल अभी भी कमरे में है!",
    },
    {
        "id": "hi-male-biography-story-17",
        "name": "Manish — Historical Biographies",
        "gender": "male",
        "category": "Storytelling",
        "style": "Inspiring & Stately",
        "description": "Stately, inspiring voice for life journeys of great leaders, freedom fighters, and historic icons.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An inspiring male narrator speaking stately Hindi for historical biographies with solemn dignity.",
        "pitch": "-4%",
        "rate": 0.94,
        "tags": ["biography", "history", "freedom", "leaders", "inspiring"],
        "preview_text": "साधारण परिस्थितियों में जन्मे इस महानायक ने अपने अदम्य साहस और दृढ़ संकल्प से देश का इतिहास बदल दिया।",
    },
    {
        "id": "hi-female-modern-audio-fiction-18",
        "name": "Riya — Pocket FM / Kuku FM Style",
        "gender": "female",
        "category": "Storytelling",
        "style": "Dramatic & Binge-Worthy",
        "description": "Modern serialized audio-novel style with heightened emotional beats and conversational intimacy.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A modern Indian female narrator delivering serialized romantic drama in Hindi with high emotional intimacy.",
        "pitch": "+2%",
        "rate": 1.00,
        "tags": ["pocketfm", "kukufm", "drama", "binge", "audio novel"],
        "preview_text": "रिया को लगा कि उसकी ज़िंदगी अब सुलझ चुकी है... लेकिन उस गुमनाम चिट्ठी ने उसके सारे अरमानों पर पानी फेर दिया।",
    },

    # =========================================================================
    # 3. YOUTUBE, REELS & SOCIAL MEDIA (19-28)
    # =========================================================================
    {
        "id": "hi-male-tech-youtuber-19",
        "name": "Sahil — Tech Reviewer",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Casual & High Energy",
        "description": "Trendy, energetic voice with natural Hinglish-friendly cadence for smartphone and gadget reviews.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An energetic Indian male YouTuber speaking Hindi in an upbeat, casual tech review style.",
        "pitch": "+4%",
        "rate": 1.08,
        "tags": ["youtube", "tech", "gadgets", "reviews", "unboxing"],
        "preview_text": "तो दोस्तों, आज के इस वीडियो में हम करने वाले हैं इस नए 5G स्मार्टफ़ोन का फुल रिव्यू और कैमरा टेस्ट!",
    },
    {
        "id": "hi-female-lifestyle-vlog-20",
        "name": "Ananya — Lifestyle Vlogger",
        "gender": "female",
        "category": "YouTube & Social",
        "style": "Bubbly & Friendly",
        "description": "Warm, cheerful, relatable voice for fashion, travel vlogs, daily routines, and food journeys.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A cheerful young Indian female speaking friendly Hindi for travel and lifestyle vlogging.",
        "pitch": "+7%",
        "rate": 1.05,
        "tags": ["vlog", "lifestyle", "travel", "food", "fashion"],
        "preview_text": "हे गाइज़! वेलकम बैक टू माय चैनल। आज मैं आपको ले जा रही हूँ जयपुर के सबसे मशहूर स्ट्रीट फ़ूड मार्केट में!",
    },
    {
        "id": "hi-male-viral-reels-21",
        "name": "Dev — Viral Shorts & Reels",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Punchy & Fast Hook",
        "description": "High-retention punchy voice optimized for 30-second Shorts, quick facts, and curiosity hooks.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A fast, punchy male voice delivering viral Hindi shorts with strong retention hooks and clean cadence.",
        "pitch": "+2%",
        "rate": 1.15,
        "tags": ["reels", "shorts", "viral", "facts", "fast"],
        "preview_text": "क्या आप जानते हैं कि दुनिया का 90% इंटरनेट डेटा समुद्र के नीचे बिछाई गई तारों से ट्रांसफर होता है?",
    },
    {
        "id": "hi-female-facts-shorts-22",
        "name": "Tanvi — Amazing Facts Girl",
        "gender": "female",
        "category": "YouTube & Social",
        "style": "Curious & Engaging",
        "description": "Curiosity-sparking female voice for psychological facts, science tidbits, and top 10 lists.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An inquisitive female voice sharing astonishing science facts in crisp Hindi with upbeat intonation.",
        "pitch": "+6%",
        "rate": 1.12,
        "tags": ["facts", "shorts", "science", "psychology", "top10"],
        "preview_text": "साइकोलॉजी के अनुसार, जब आप किसी को याद करते हैं, तो 80% चांस है कि वो इंसान भी आपके बारे में सोच रहा हो!",
    },
    {
        "id": "hi-male-gaming-streamer-23",
        "name": "Karan — Gaming Streamer",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Hype & Reaction",
        "description": "High-octane, hype-filled voice for game walkthroughs, e-sports commentary, and reaction clips.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A hyped male gaming streamer speaking fast conversational Hindi with excitement and peak energy.",
        "pitch": "+8%",
        "rate": 1.12,
        "tags": ["gaming", "esports", "reaction", "hype", "streamer"],
        "preview_text": "ओह भाई साहब! क्या क्लच मारा है यहाँ पे! बिल्कुल एक एचपी पे पूरी स्क्वॉड साफ़ कर दी!",
    },
    {
        "id": "hi-female-motivation-shorts-24",
        "name": "Isha — Daily Affirmations & Shorts",
        "gender": "female",
        "category": "YouTube & Social",
        "style": "Empowering & Clear",
        "description": "Clear, empowering delivery for morning motivation, fitness quotes, and personal growth shorts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A confident female voice delivering uplifting Hindi motivation with clarity and positive conviction.",
        "pitch": "+3%",
        "rate": 1.00,
        "tags": ["motivation", "quotes", "growth", "positivity", "fitness"],
        "preview_text": "याद रखिए, मुश्किल रास्ते ही अक्सर सबसे खूबसूरत मंज़िलों की तरफ़ ले जाते हैं। कभी हार मत मानिए।",
    },
    {
        "id": "hi-male-finance-fintech-25",
        "name": "Akash — Personal Finance Creator",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Credible & Explanatory",
        "description": "Trustworthy, conversational voice explaining taxes, stock SIPs, credit cards, and wealth habits.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A knowledgeable Indian male talking about money and investing in simple, trustworthy Hindi.",
        "pitch": "-2%",
        "rate": 1.04,
        "tags": ["finance", "money", "investing", "sip", "creator"],
        "preview_text": "अगर आप हर महीने सिर्फ़ 2000 रुपये का एसआईपी शुरू करते हैं, तो 15 साल में आपका रिटर्न देखकर आप चौंक जाएंगे।",
    },
    {
        "id": "hi-female-diy-crafts-26",
        "name": "Simran — DIY & Craft Guide",
        "gender": "female",
        "category": "YouTube & Social",
        "style": "Step-by-Step & Friendly",
        "description": "Patient, sweet-toned voice guiding viewers through recipes, home decor, and craft hacks.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A friendly female voice guiding home crafts and cooking recipes step by step in clear Hindi.",
        "pitch": "+5%",
        "rate": 0.96,
        "tags": ["diy", "cooking", "craft", "recipes", "home"],
        "preview_text": "सबसे पहले हम एक साफ़ बाउल में दो चम्मच बेसन लेंगे और उसमें हल्का सा गुनगुना पानी मिलाएंगे।",
    },
    {
        "id": "hi-male-movie-recap-27",
        "name": "Raghav — Cinema & Movie Recap",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Intriguing & Fast Narrative",
        "description": "Deep, intriguing pacing tuned specifically for 10-minute cinema recaps and plot summaries.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A male movie recap narrator speaking Hindi with intriguing tone, brisk pacing, and suspense.",
        "pitch": "-7%",
        "rate": 1.08,
        "tags": ["movie recap", "cinema", "plot", "summary", "film"],
        "preview_text": "फ़िल्म की शुरुआत में हम देखते हैं कि नायक एक बंजर द्वीप पर फंसा हुआ है और उसके पास सिर्फ़ एक टूटी हुई घड़ी है।",
    },
    {
        "id": "hi-female-book-summary-28",
        "name": "Vandana — Book Summary Host",
        "gender": "female",
        "category": "YouTube & Social",
        "style": "Articulate & Intellectual",
        "description": "Articulate, calming delivery for self-help book summaries, productivity tips, and book clubs.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An articulate female voice presenting book takeaways in Hindi with clarity and calm intelligence.",
        "pitch": "+0%",
        "rate": 0.98,
        "tags": ["books", "summary", "productivity", "self help"],
        "preview_text": "आज की इस बेस्टसेलर किताब का सबसे बड़ा सबक़ यह है कि छोटी-छोटी आदतें मिलकर बड़ा बदलाव लाती हैं।",
    },

    # =========================================================================
    # 4. ADVERTISEMENTS & COMMERCIALS (29-38)
    # =========================================================================
    {
        "id": "hi-male-ad-luxury-29",
        "name": "Samar — Luxury & Premium Brand",
        "gender": "male",
        "category": "Advertisements",
        "style": "Smooth & Sophisticated",
        "description": "Ultra-smooth, velvet baritone voice for luxury cars, premium real estate, and high-end perfumes.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A deep, sophisticated male voice speaking luxurious Hindi with whisper-soft velvet tone and rich bass.",
        "pitch": "-15%",
        "rate": 0.88,
        "tags": ["luxury", "ad", "commercial", "perfume", "premium"],
        "preview_text": "जहाँ हर लम्हा एक ख़ास अहसास बन जाए। पेश है शुद्ध नफ़ासत और बेमिसाल विलासिता का नया नाम।",
    },
    {
        "id": "hi-female-ad-beauty-30",
        "name": "Natasha — Beauty & Skincare",
        "gender": "female",
        "category": "Advertisements",
        "style": "Silky & Persuasive",
        "description": "Silky, intimate voice ideal for cosmetics, glowing skincare, spa promotions, and salon ads.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A silky, gentle female voice whispering beauty secrets in Hindi with warm intimacy and clarity.",
        "pitch": "+1%",
        "rate": 0.92,
        "tags": ["beauty", "skincare", "cosmetics", "ad", "commercial"],
        "preview_text": "आपकी त्वचा को मिले 24 घंटे का प्राकृतिक निखार और नमी। क्योंकि आपकी खूबसूरती है अनमोल।",
    },
    {
        "id": "hi-male-ad-festive-sale-31",
        "name": "Ajay — Mega Festive Sale",
        "gender": "male",
        "category": "Advertisements",
        "style": "Booming & High Impact",
        "description": "Thunderous, celebratory sale announcement voice for Diwali, Big Billion Days, and retail blowouts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A booming energetic male voice announcing a massive festive shopping sale in Hindi with excitement.",
        "pitch": "+4%",
        "rate": 1.12,
        "tags": ["sale", "festive", "diwali", "shopping", "discount"],
        "preview_text": "इस दिवाली, खुशियों का महा-धमाका! पाएँ पूरे 80% तक की भारी छूट सभी इलेक्ट्रॉनिक्स और कपड़ों पर!",
    },
    {
        "id": "hi-female-ad-fmcg-32",
        "name": "Deepika — Family FMCG & Food",
        "gender": "female",
        "category": "Advertisements",
        "style": "Warm & Wholesome",
        "description": "Wholesome, caring motherly tone for cooking oils, spices, tea brands, and family nutrition.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A warm, caring Indian mother voice recommending pure spices and wholesome food in Hindi.",
        "pitch": "+3%",
        "rate": 0.98,
        "tags": ["fmcg", "family", "food", "spices", "wholesome"],
        "preview_text": "घर का वही शुद्ध स्वाद और ममता का प्यार, जो हर निवाले को बनाए सेहतमंद और लज़ीज़।",
    },
    {
        "id": "hi-male-ad-automotive-33",
        "name": "Arjun — Automotive & Power",
        "gender": "male",
        "category": "Advertisements",
        "style": "Rugged & Powerful",
        "description": "Gravelly, rugged male voice built for SUV launches, heavy machinery, motor oil, and adventure gear.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A rugged male voice with deep gravelly tone narrating an SUV car commercial in Hindi with raw power.",
        "pitch": "-12%",
        "rate": 0.95,
        "tags": ["automotive", "suv", "rugged", "power", "adventure"],
        "preview_text": "ना कोई रुकावट, ना कोई समझौता। जो हर मुश्किल रास्ते को अपनी मंज़िल बना ले — यह है असली ताक़त।",
    },
    {
        "id": "hi-female-ad-fashion-34",
        "name": "Kareena — Trendy Apparel",
        "gender": "female",
        "category": "Advertisements",
        "style": "Chic & Modern",
        "description": "Upbeat, fashionable delivery for Gen-Z apparel, sneaker drops, eyewear, and urban lifestyle.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A chic and modern Indian female voice speaking fashionable Hindi for trendy apparel brands.",
        "pitch": "+5%",
        "rate": 1.06,
        "tags": ["fashion", "apparel", "chic", "modern", "clothing"],
        "preview_text": "अपना अंदाज़, अपनी पहचान। इस सीज़न के सबसे हॉट फ़ैशन ट्रेंड्स अब आपके पसंदीदा स्टोर पर उपलब्ध हैं।",
    },
    {
        "id": "hi-male-ad-pharma-wellness-35",
        "name": "Dr. Naresh — Health & Pharma",
        "gender": "male",
        "category": "Advertisements",
        "style": "Reassuring & Credible",
        "description": "Calm, medical-grade reassurance for pain relief balms, vitamins, health insurance, and dental care.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A trustworthy male medical doctor tone giving health advice in clear, compassionate Hindi.",
        "pitch": "-3%",
        "rate": 0.96,
        "tags": ["health", "pharma", "medicine", "doctor", "wellness"],
        "preview_text": "तेज़ सिरदर्द या जोड़ों का दर्द? अब पाइए तुरंत और भरोसेमंद आराम, ताकि आपका दिन कभी न थमे।",
    },
    {
        "id": "hi-female-ad-banking-loan-36",
        "name": "Sangeeta — Bank & Home Loan",
        "gender": "female",
        "category": "Advertisements",
        "style": "Friendly & Trustworthy",
        "description": "Welcoming, reliable voice for low-interest home loans, fixed deposits, and banking apps.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A friendly banking advisor female speaking Hindi with warmth and financial trustworthiness.",
        "pitch": "+2%",
        "rate": 1.00,
        "tags": ["banking", "loans", "finance", "trust", "money"],
        "preview_text": "अपने सपनों का घर बसाना अब हुआ और भी आसान। सबसे कम ब्याज दरों और ज़ीरो प्रोसेसिंग फ़ीस के साथ।",
    },
    {
        "id": "hi-male-ad-radio-jingle-37",
        "name": "Bunty — Quirky Radio Spot",
        "gender": "male",
        "category": "Advertisements",
        "style": "Comedic & Quirky",
        "description": "High-pitched comedic voice with Delhi/Mumbai street flavor for humorous radio skits.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A comedic Indian male voice speaking humorous street-smart Hindi for a funny radio commercial.",
        "pitch": "+9%",
        "rate": 1.10,
        "tags": ["comedy", "quirky", "radio", "humor", "jingle"],
        "preview_text": "अरे भाई! जब आधी कीमत में मिल रहा है असली माल, तो क्यों कर रहे हो अपना दिमाग़ ख़राब?",
    },
    {
        "id": "hi-female-ad-kids-toy-38",
        "name": "Guddi — Toys & Confectionery",
        "gender": "female",
        "category": "Advertisements",
        "style": "Playful & Cheerful",
        "description": "Bright, sugar-coated excitement for chocolate bars, fruit juices, theme parks, and cartoon toys.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A bright cheerful female voice advertising chocolates and toys to kids in exciting Hindi.",
        "pitch": "+11%",
        "rate": 1.06,
        "tags": ["kids", "toys", "candy", "chocolate", "fun"],
        "preview_text": "मस्ती का नया फ्लेवर! हर बाइट में छिपा है चॉकलेट का अद्भुत धमाका, जिसे खाकर आप कहेंगे — वाह!",
    },

    # =========================================================================
    # 5. DOCUMENTARIES & HISTORY (39-46)
    # =========================================================================
    {
        "id": "hi-male-doc-wildlife-39",
        "name": "Pratap — Wildlife & Nature",
        "gender": "male",
        "category": "Documentary",
        "style": "Deep Nature Explorer",
        "description": "BBC / National Geographic style Hindi narrator for tiger reserves, deep oceans, and jungles.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A deep majestic male wildlife narrator speaking Hindi in National Geographic style with hushed grandeur.",
        "pitch": "-14%",
        "rate": 0.88,
        "tags": ["wildlife", "nature", "natgeo", "jungle", "animals"],
        "preview_text": "घने जंगलों के सन्नाटे में, बंगाल टाइगर अपनी गुप्त निगाहों से शिकार की हर हरकत पर नज़र गड़ाए बैठा है...",
    },
    {
        "id": "hi-female-doc-geography-40",
        "name": "Uma — Earth & Space Explainer",
        "gender": "female",
        "category": "Documentary",
        "style": "Majestic & Serene",
        "description": "Serene, awe-inspiring female voice exploring galaxies, black holes, volcanoes, and planet Earth.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A serene female voice narrating space and planetary documentaries in Hindi with wonder and majesty.",
        "pitch": "-3%",
        "rate": 0.90,
        "tags": ["space", "earth", "science", "astronomy", "cosmos"],
        "preview_text": "अरबों प्रकाश वर्ष दूर, इस असीम ब्रह्मांड में अनगिनत तारे जन्म लेते हैं और महाविस्फोट में विलीन हो जाते हैं।",
    },
    {
        "id": "hi-male-doc-ancient-history-41",
        "name": "Shastri — Ancient Indian Dynasties",
        "gender": "male",
        "category": "Documentary",
        "style": "Scholarly & Profound",
        "description": "Profound, scholarly baritone narrating Indus Valley, Maurya, Gupta, and Chola empires.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A scholarly male voice narrating Indian ancient history in pure, dignified Hindi with historical gravity.",
        "pitch": "-10%",
        "rate": 0.92,
        "tags": ["history", "ancient", "dynasties", "india", "archaeology"],
        "preview_text": "हड़प्पा और मोहनजोदड़ो के खंडहर आज भी उस प्राचीन सिंधु-सरस्वती सभ्यता के उन्नत नगर-नियोजन की गवाही देते हैं।",
    },
    {
        "id": "hi-female-doc-cultural-heritage-42",
        "name": "Madhavi — Art & Monument Heritage",
        "gender": "female",
        "category": "Documentary",
        "style": "Graceful & Rich",
        "description": "Graceful, culturally rich narration for UNESCO monuments, temple architecture, and classical arts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A graceful female narrator describing Indian heritage and architecture in poetic, articulate Hindi.",
        "pitch": "+0%",
        "rate": 0.94,
        "tags": ["heritage", "unesco", "temples", "architecture", "culture"],
        "preview_text": "खजुराहो और कोणार्क के पत्थरों पर तराशी गई ये मूर्तियाँ मात्र कला नहीं, बल्कि उस युग के दर्शन का दर्पण हैं।",
    },
    {
        "id": "hi-male-doc-military-history-43",
        "name": "Col. Ranjit — Battles & Defense",
        "gender": "male",
        "category": "Documentary",
        "style": "Stern & Resolute",
        "description": "Resolute, disciplined military tone narrating 1971 war heroics, Kargil battles, and tactical operations.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A stern, resolute male voice narrating military defense history in Hindi with patriotic discipline.",
        "pitch": "-8%",
        "rate": 0.96,
        "tags": ["military", "war", "kargil", "army", "defense"],
        "preview_text": "माइनस 30 डिग्री की हाड़ कंपाने वाली ठंड और खड़ी चट्टानों पर चढ़ते हुए भारतीय सैनिकों ने उस चोटी पर तिरंगा लहराया।",
    },
    {
        "id": "hi-female-doc-ocean-life-44",
        "name": "Nandita — Deep Sea Mysteries",
        "gender": "female",
        "category": "Documentary",
        "style": "Hushed & Atmospheric",
        "description": "Atmospheric, hushed delivery taking listeners into the abyss of coral reefs and deep trenches.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A soft atmospheric female voice narrating marine biology and underwater depths in calming Hindi.",
        "pitch": "-4%",
        "rate": 0.88,
        "tags": ["ocean", "marine", "underwater", "nature", "coral"],
        "preview_text": "समुद्र की अथाह गहराइयों में, जहाँ सूरज की एक किरण भी नहीं पहुँचती, वहाँ जीवन के अनोखे रूप पनपते हैं।",
    },
    {
        "id": "hi-male-doc-crime-investigation-45",
        "name": "Siddharth — Real Crime Chronicles",
        "gender": "male",
        "category": "Documentary",
        "style": "Investigative & Gritty",
        "description": "Gritty, forensic realism for investigative true crime podcasts, forensic casefiles, and heists.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A gritty investigative male voice detailing forensic crime files in Hindi with serious tone.",
        "pitch": "-9%",
        "rate": 0.94,
        "tags": ["crime", "investigation", "forensics", "casefiles", "police"],
        "preview_text": "घटनास्थल से मिले उन अधूरे उंगलियों के निशानों ने इस पेचीदा केस को एक नया और चौंकाने वाला मोड़ दे दिया।",
    },
    {
        "id": "hi-female-doc-social-issues-46",
        "name": "Aruna — Social Change & Society",
        "gender": "female",
        "category": "Documentary",
        "style": "Empathetic & Serious",
        "description": "Empathetic, earnest documentary voice addressing rural health, education, and women empowerment.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An earnest, empathetic female narrator addressing social reforms and grassroots change in Hindi.",
        "pitch": "-1%",
        "rate": 0.95,
        "tags": ["social", "reform", "society", "grassroots", "earnest"],
        "preview_text": "जब गाँव की बेटियों को पहली बार शिक्षा का अवसर मिला, तो उन्होंने पूरे समुदाय की तकदीर बदल कर रख दी।",
    },

    # =========================================================================
    # 6. EDUCATIONAL & E-LEARNING (47-56)
    # =========================================================================
    {
        "id": "hi-male-edu-upsc-sir-47",
        "name": "Prof. Verma — Civil Services & UPSC",
        "gender": "male",
        "category": "Educational",
        "style": "Academic & Authoritative",
        "description": "Patient, clear professor voice breaking down Indian constitution, polity, and history for UPSC aspirants.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An academic Indian male professor lecturing on Indian polity in clear, authoritative Hindi.",
        "pitch": "-4%",
        "rate": 0.96,
        "tags": ["upsc", "polity", "education", "professor", "exam"],
        "preview_text": "संविधान के अनुच्छेद 21 के तहत दिए गए प्राण और दैहिक स्वतंत्रता के अधिकार का दायरा अत्यंत व्यापक है।",
    },
    {
        "id": "hi-female-edu-school-teacher-48",
        "name": "Rashmi Ma'am — Primary School Tutor",
        "gender": "female",
        "category": "Educational",
        "style": "Warm & Encouraging",
        "description": "Encouraging, clear-voiced school teacher perfect for grammar, math basics, and children's science lessons.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A warm, patient female school teacher explaining concepts in simple, sweet Hindi to students.",
        "pitch": "+5%",
        "rate": 0.92,
        "tags": ["school", "teacher", "kids", "grammar", "math"],
        "preview_text": "नमस्ते बच्चों! आज हम सीखेंगे कि प्रकाश संश्लेषण की प्रक्रिया में पौधे अपना भोजन कैसे तैयार करते हैं।",
    },
    {
        "id": "hi-male-edu-stem-physics-49",
        "name": "Gaurav Sir — Physics & Engineering",
        "gender": "male",
        "category": "Educational",
        "style": "Crisp & Analytical",
        "description": "Analytical STEM tutor voice explaining thermodynamics, Newton's laws, and coding algorithms in Hindi.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An analytical male instructor explaining physics and engineering concepts in crisp Hindi.",
        "pitch": "+0%",
        "rate": 1.00,
        "tags": ["physics", "engineering", "stem", "coding", "analytical"],
        "preview_text": "जब किसी वस्तु पर बाहरी बल लगाया जाता है, तो उसके संवेग परिवर्तन की दर लगाए गए बल के समानुपाती होती है।",
    },
    {
        "id": "hi-female-edu-biology-50",
        "name": "Dr. Shalini — Biology & Medicine",
        "gender": "female",
        "category": "Educational",
        "style": "Precise & Articulate",
        "description": "Precise medical tutor articulation for human anatomy, genetics, and biotechnology modules.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A precise female biology lecturer teaching human physiology in clear, articulate Hindi.",
        "pitch": "+2%",
        "rate": 0.98,
        "tags": ["biology", "medical", "neet", "physiology", "science"],
        "preview_text": "मानव हृदय में चार प्रमुख कक्ष होते हैं, जो शरीर में शुद्ध और अशुद्ध रक्त के परिसंचरण को नियंत्रित करते हैं।",
    },
    {
        "id": "hi-male-edu-history-lecturer-51",
        "name": "Dr. Tripathi — World & Indian History",
        "gender": "male",
        "category": "Educational",
        "style": "Eloquent & Narrative",
        "description": "Eloquent lecture style that turns historical dates into vivid, memorable stories.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An eloquent male history teacher lecturing on Indian freedom struggle in engaging Hindi.",
        "pitch": "-5%",
        "rate": 0.94,
        "tags": ["history", "lecture", "freedom struggle", "eloquent"],
        "preview_text": "1857 के प्रथम स्वतंत्रता संग्राम ने पूरे देश में ब्रिटिश हुकूमत के ख़िलाफ़ आज़ादी की नई अलख जगा दी थी।",
    },
    {
        "id": "hi-female-edu-literature-52",
        "name": "Sudha — Hindi Sahitya & Kavita",
        "gender": "female",
        "category": "Educational",
        "style": "Poetic & Articulate",
        "description": "Pure Shuddh Hindi pronunciation for Hindi literature, poetry explanation, and Chhayavad criticism.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A scholarly female Hindi literature teacher reciting poetry and explaining metaphors with rich diction.",
        "pitch": "-1%",
        "rate": 0.90,
        "tags": ["literature", "sahitya", "poetry", "kavita", "shuddh hindi"],
        "preview_text": "महाकवि निराला की इस कविता में प्रकृति के माध्यम से मानव मन के अंतर्द्वंद्व को अत्यंत सजीव रूप में उकेरा गया है।",
    },
    {
        "id": "hi-male-edu-coding-tech-53",
        "name": "Naveen — Python & Web Dev Tutor",
        "gender": "male",
        "category": "Educational",
        "style": "Practical & Conversational",
        "description": "Tech-savvy instructor voice explaining data structures, Python loops, and web apps with ease.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A practical young Indian male explaining programming tutorials in easy conversational Hindi.",
        "pitch": "+2%",
        "rate": 1.04,
        "tags": ["coding", "python", "programming", "software", "web dev"],
        "preview_text": "यहाँ हम एक फंक्शन डिफाइन करेंगे, जो इनपुट डेटा को प्रोसेस करके हमें सटीक रिजल्ट रिटर्न करेगा।",
    },
    {
        "id": "hi-female-edu-english-speaking-54",
        "name": "Kiran — Spoken English for Hindi Speakers",
        "gender": "female",
        "category": "Educational",
        "style": "Clear & Bilingual",
        "description": "Clear bilingual cadence guiding Hindi speakers through spoken English idioms and pronunciation.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A clear female language instructor teaching spoken communication skills in bilingual Hindi.",
        "pitch": "+4%",
        "rate": 0.96,
        "tags": ["language", "english learning", "bilingual", "communication"],
        "preview_text": "जब भी आप किसी नए व्यक्ति से मिलें, तो आत्मविश्वास के साथ कहें — 'नाइस टू मीट यू', यानी आपसे मिलकर ख़ुशी हुई।",
    },
    {
        "id": "hi-male-edu-exam-strategy-55",
        "name": "Vipin Sir — Motivation & Exam Tips",
        "gender": "male",
        "category": "Educational",
        "style": "Energetic Mentor",
        "description": "High-spirit coaching mentor encouraging students through exam stress, time tables, and revision hacks.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An energetic exam mentor speaking motivating Hindi to encourage students preparing for competitive exams.",
        "pitch": "+3%",
        "rate": 1.06,
        "tags": ["exam", "motivation", "coaching", "strategy", "revision"],
        "preview_text": "अगर आप आज 8 घंटे मेहनत करने को तैयार नहीं हैं, तो कल अपने सपनों से समझौता करने के लिए तैयार रहिए!",
    },
    {
        "id": "hi-female-edu-moral-values-56",
        "name": "Bhavna — Moral Science & Ethics",
        "gender": "female",
        "category": "Educational",
        "style": "Gentle & Inspiring",
        "description": "Gentle, ethical guidance voice for school value education, empathy lessons, and civics.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A gentle female voice teaching ethics and compassion in Hindi with calming inspiration.",
        "pitch": "+1%",
        "rate": 0.94,
        "tags": ["ethics", "values", "morals", "kindness", "gentle"],
        "preview_text": "सच्ची सफलता सिर्फ़ अच्छे अंकों में नहीं, बल्कि इस बात में है कि आप दूसरों के प्रति कितने दयालु और ईमानदार हैं।",
    },

    # =========================================================================
    # 7. CORPORATE & BUSINESS (57-66)
    # =========================================================================
    {
        "id": "hi-male-corp-ceo-57",
        "name": "Rajiv — Executive Keynote & CEO",
        "gender": "male",
        "category": "Corporate",
        "style": "Commanding & Visionary",
        "description": "Visionary executive baritone for annual general meetings, corporate vision videos, and leadership summits.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A commanding male CEO delivering a corporate keynote speech in refined, visionary Hindi.",
        "pitch": "-7%",
        "rate": 0.96,
        "tags": ["ceo", "keynote", "corporate", "leadership", "executive"],
        "preview_text": "नवाचार और निरंतर उत्कृष्टता के प्रति हमारी प्रतिबद्धता ने हमें इस वर्ष उद्योग में शीर्ष स्थान पर पहुँचाया है।",
    },
    {
        "id": "hi-female-corp-hr-training-58",
        "name": "Priyanka — HR Onboarding & Compliance",
        "gender": "female",
        "category": "Corporate",
        "style": "Welcoming & Professional",
        "description": "Warm, professional corporate voice for employee onboarding, compliance policies, and POSH training.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A professional female HR manager presenting company onboarding policies in clear, welcoming Hindi.",
        "pitch": "+2%",
        "rate": 0.98,
        "tags": ["hr", "onboarding", "training", "compliance", "corporate"],
        "preview_text": "हमारी कंपनी के परिवार में आपका हार्दिक स्वागत है। आइए, हमारे कार्यस्थल की नीतियों और संस्कृति को समझें।",
    },
    {
        "id": "hi-male-corp-quarterly-results-59",
        "name": "Alok — Financial Results & Investor Call",
        "gender": "male",
        "category": "Corporate",
        "style": "Sober & Data-Driven",
        "description": "Precise, data-oriented tone for quarterly earnings, EBIDTA reports, and audit disclosures.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A sober, articulate male corporate executive presenting quarterly financial earnings in Hindi.",
        "pitch": "-3%",
        "rate": 1.00,
        "tags": ["earnings", "investor", "financial", "quarterly", "data"],
        "preview_text": "वर्तमान तिमाही में हमारे कुल राजस्व में 18 प्रतिशत की शुद्ध वृद्धि दर्ज की गई है, जिससे शेयरधारकों का विश्वास और मजबूत हुआ है।",
    },
    {
        "id": "hi-female-corp-sales-pitch-60",
        "name": "Pallavi — Enterprise B2B Sales",
        "gender": "female",
        "category": "Corporate",
        "style": "Persuasive & Polished",
        "description": "Confident, polished business presentation voice for client proposals, SaaS demos, and pitch decks.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A confident female enterprise sales executive presenting software solutions in persuasive Hindi.",
        "pitch": "+3%",
        "rate": 1.02,
        "tags": ["sales", "b2b", "pitch", "enterprise", "proposal"],
        "preview_text": "हमारा यह क्लाउड प्लेटफ़ॉर्म आपके व्यावसायिक ऑपरेशन्स की कार्यक्षमता को दोगुना करने में पूरी तरह सक्षम है।",
    },
    {
        "id": "hi-male-corp-tech-explainer-61",
        "name": "Sanjay — IT & Digital Transformation",
        "gender": "male",
        "category": "Corporate",
        "style": "Clear & Modern",
        "description": "Modern technical voice explaining cloud migration, cybersecurity, and AI integration to corporate teams.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A modern male IT consultant explaining digital transformation in clear business Hindi.",
        "pitch": "-1%",
        "rate": 1.00,
        "tags": ["it", "tech", "digital", "consulting", "cybersecurity"],
        "preview_text": "साइबर सुरक्षा और डेटा गोपनीयता आज के डिजिटल युग में किसी भी संगठन की सर्वोच्च प्राथमिकता होनी चाहिए।",
    },
    {
        "id": "hi-female-corp-product-launch-62",
        "name": "Aditi — Product Launch Host",
        "gender": "female",
        "category": "Corporate",
        "style": "Sophisticated & Dynamic",
        "description": "Dynamic, sleek voice for brand showcases, investor demo days, and new product announcements.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A dynamic female corporate presenter introducing a new flagship product in sophisticated Hindi.",
        "pitch": "+4%",
        "rate": 1.04,
        "tags": ["launch", "product", "demo", "event", "showcase"],
        "preview_text": "आज हमें गर्व है कि हम आपके सामने अपनी इस नई क्रांतिकारी तकनीक का अनावरण कर रहे हैं।",
    },
    {
        "id": "hi-male-corp-safety-training-63",
        "name": "Dinesh — Industrial Safety & EHS",
        "gender": "male",
        "category": "Corporate",
        "style": "Authoritative & Strict",
        "description": "Firm, safety-first cadence for plant operations, factory floor protocol, and emergency drills.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An authoritative male safety officer explaining industrial factory safety guidelines in Hindi.",
        "pitch": "-6%",
        "rate": 0.94,
        "tags": ["safety", "factory", "industrial", "protocol", "ehs"],
        "preview_text": "कार्यक्षेत्र में हेलमेट और सुरक्षात्मक दस्ताने पहनना अनिवार्य है। किसी भी आपात स्थिति में अलार्म का तुरंत उपयोग करें।",
    },
    {
        "id": "hi-female-corp-csr-impact-64",
        "name": "Geeta — CSR & Sustainability",
        "gender": "female",
        "category": "Corporate",
        "style": "Inspiring & Compassionate",
        "description": "Inspiring, socially conscious delivery for annual CSR reports, green initiatives, and philanthropy.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An inspiring female voice narrating corporate sustainability and community social impact in Hindi.",
        "pitch": "+0%",
        "rate": 0.96,
        "tags": ["csr", "sustainability", "green", "community", "social impact"],
        "preview_text": "पर्यावरण संरक्षण और ग्रामीण विकास के प्रति हमारे निरंतर प्रयासों से अब तक हज़ारों परिवारों के जीवन में सुधार आया है।",
    },
    {
        "id": "hi-male-corp-internal-podcast-65",
        "name": "Harish — Internal Townhall & Podcast",
        "gender": "male",
        "category": "Corporate",
        "style": "Friendly & Engaging",
        "description": "Conversational yet professional cadence for company townhalls, newsletters, and internal podcasts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A friendly male internal communications host talking to company employees in conversational Hindi.",
        "pitch": "-2%",
        "rate": 1.00,
        "tags": ["townhall", "newsletter", "podcast", "internal", "team"],
        "preview_text": "इस महीने के हमारे मासिक टाउनहॉल में आप सभी का स्वागत है। आइए जानते हैं हमारी टीमों की सबसे बड़ी उपलब्धियाँ।",
    },
    {
        "id": "hi-female-corp-recruitment-66",
        "name": "Juhi — Talent Acquisition & Careers",
        "gender": "female",
        "category": "Corporate",
        "style": "Inviting & Energetic",
        "description": "Vibrant, inviting employer brand voice for careers pages, hiring drives, and campus outreach.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An inviting female corporate recruiter inviting top talent to join the company in upbeat Hindi.",
        "pitch": "+3%",
        "rate": 1.02,
        "tags": ["hiring", "recruitment", "careers", "jobs", "talent"],
        "preview_text": "क्या आप अपने करियर को नई ऊँचाइयों पर ले जाने के लिए तैयार हैं? हमारे साथ जुड़िए और भविष्य का निर्माण कीजिए।",
    },

    # =========================================================================
    # 8. PODCASTS & CONVERSATIONAL (67-74)
    # =========================================================================
    {
        "id": "hi-male-podcast-late-night-67",
        "name": "Neil — Late Night Radio & Podcast",
        "gender": "male",
        "category": "Podcasts",
        "style": "Warm & Mellow",
        "description": "Velvety, intimate RJ voice akin to late-night radio shows talking about relationships, life, and nostalgia.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A warm, mellow male radio jockey whispering life reflections in Hindi with deep late-night intimacy.",
        "pitch": "-12%",
        "rate": 0.88,
        "tags": ["podcast", "late night", "rj", "radio", "intimate"],
        "preview_text": "रात के सन्नाटे में जब शहर सो जाता है, तो यादों का एक पुराना कारवां दिल के दरवाज़े पर दस्तक देता है...",
    },
    {
        "id": "hi-female-podcast-cozy-talk-68",
        "name": "Chhavi — Cozy Coffee Chat",
        "gender": "female",
        "category": "Podcasts",
        "style": "Casual & Intimate",
        "description": "Natural, intimate friend voice discussing mental wellness, book recommendations, and everyday thoughts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A relaxed female podcaster talking to a friend over coffee in natural, warm conversational Hindi.",
        "pitch": "+1%",
        "rate": 0.96,
        "tags": ["podcast", "casual", "chat", "wellness", "friend"],
        "preview_text": "हाय दोस्तों, आज एक कप चाय के साथ हम बात करेंगे उस एक डर के बारे में जो हम सब कभी न कभी महसूस करते हैं।",
    },
    {
        "id": "hi-male-podcast-interviewer-69",
        "name": "Shekhar — Deep-Dive Interviewer",
        "gender": "male",
        "category": "Podcasts",
        "style": "Inquisitive & Thoughtful",
        "description": "Thoughtful, respectful host cadence for long-form podcasts featuring startup founders, artists, and scholars.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An inquisitive male podcast host conducting a thoughtful interview in articulate Hindi.",
        "pitch": "-4%",
        "rate": 0.98,
        "tags": ["interview", "podcast", "founders", "deep dive", "inquisitive"],
        "preview_text": "आज हमारे साथ एक ऐसे ख़ास मेहमान हैं जिन्होंने शून्य से शुरुआत करके देश के सबसे बड़े स्टार्टअप की नींव रखी।",
    },
    {
        "id": "hi-female-podcast-true-stories-70",
        "name": "Krittika — Human Stories & Real Life",
        "gender": "female",
        "category": "Podcasts",
        "style": "Emotive & Unfiltered",
        "description": "Deeply empathetic, unfiltered voice exploring real human struggles, survival tales, and triumphs.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An emotive female storytelling podcaster narrating real human experiences in Hindi with sensitivity.",
        "pitch": "-2%",
        "rate": 0.94,
        "tags": ["human stories", "real life", "empathy", "struggle", "podcast"],
        "preview_text": "जब ज़िंदगी के सारे रास्ते बंद नज़र आ रहे थे, तब एक छोटी सी उम्मीद ने उनकी पूरी दुनिया को बदल कर रख दिया।",
    },
    {
        "id": "hi-male-podcast-chai-adda-71",
        "name": "Bittu — Chai Pe Charcha",
        "gender": "male",
        "category": "Podcasts",
        "style": "Street-Smart & Humorous",
        "description": "Street-smart, witty cadence for relatable banter, cinema gossip, and comedic buddy podcasts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A witty and humorous young Indian male hosting a casual buddy podcast in Delhi Hindi dialect.",
        "pitch": "+4%",
        "rate": 1.06,
        "tags": ["banter", "comedy", "chai", "buddy", "funny"],
        "preview_text": "गुरु, आज का टॉपिक इतना मसालेदार है कि सुनते ही आपकी चाय ठंडी हो जाएगी लेकिन चर्चा गरम रहेगी!",
    },
    {
        "id": "hi-female-podcast-cinema-critic-72",
        "name": "Shilpa — Film Critic & Pop Culture",
        "gender": "female",
        "category": "Podcasts",
        "style": "Analytical & Entertaining",
        "description": "Witty, sharp critique tone analyzing Bollywood releases, OTT shows, and global cinema.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A sharp female film critic sharing witty movie reviews and OTT critiques in fluent Hindi.",
        "pitch": "+2%",
        "rate": 1.02,
        "tags": ["cinema", "critic", "bollywood", "ott", "pop culture"],
        "preview_text": "फ़िल्म की कहानी जितनी दमदार थी, उसका स्क्रीनप्ले उतना ही कमज़ोर साबित हुआ। आइए करते हैं इसका पूरा विश्लेषण।",
    },
    {
        "id": "hi-male-podcast-philosophy-73",
        "name": "Acharya Satya — Thought & Philosophy",
        "gender": "male",
        "category": "Podcasts",
        "style": "Calm & Contemplative",
        "description": "Contemplative, serene voice examining life philosophy, mindfulness, and timeless wisdom.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A contemplative male philosopher speaking in a deeply calm, meditative Hindi cadence.",
        "pitch": "-10%",
        "rate": 0.88,
        "tags": ["philosophy", "wisdom", "mindfulness", "calm", "contemplative"],
        "preview_text": "मन जब भूतकाल के पछतावे और भविष्य की चिंताओं से मुक्त होता है, तभी वर्तमान के वास्तविक आनंद की अनुभूति होती है।",
    },
    {
        "id": "hi-female-podcast-myth-buster-74",
        "name": "Pooja — Superstition & Myth Buster",
        "gender": "female",
        "category": "Podcasts",
        "style": "Direct & Rational",
        "description": "Rational, scientific tone debunking urban myths, fake WhatsApp forwards, and pseudoscience.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A rational female podcaster debunking scientific myths in clear, evidence-based Hindi.",
        "pitch": "+1%",
        "rate": 1.02,
        "tags": ["science", "myths", "rational", "evidence", "debunk"],
        "preview_text": "आज हम विज्ञान की कसौटी पर परखेंगे उन भ्रांतियों को, जिन्हें हम बचपन से सच मानते आ रहे थे।",
    },

    # =========================================================================
    # 9. MEDITATION, WELLNESS & SPIRITUAL (75-82)
    # =========================================================================
    {
        "id": "hi-female-meditation-breathing-75",
        "name": "Anandi — Guided Breathwork & Yoga",
        "gender": "female",
        "category": "Meditation",
        "style": "Tranquil & Soothing",
        "description": "Hypnotic, breath-centered guidance voice for Pranayama, mindfulness meditation, and stress relief.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A peaceful female meditation guru speaking slow, soothing Hindi with tranquil breath pacing.",
        "pitch": "-4%",
        "rate": 0.82,
        "tags": ["meditation", "breathwork", "yoga", "peace", "calm"],
        "preview_text": "अपनी आँखें धीरे से बंद करें... एक गहरी, लंबी सांस अंदर लें... और सारे तनाव को बाहर छोड़ दें...",
    },
    {
        "id": "hi-male-meditation-sleep-story-76",
        "name": "Somesh — Sleep Story & Insomnia Guide",
        "gender": "male",
        "category": "Meditation",
        "style": "Deep & Hypnotic",
        "description": "Ultra-low, hypnotic baritone whispering gentle dreamscapes to help listeners fall into deep sleep.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A deep hypnotic male sleep guide speaking slow, gentle Hindi designed to induce deep relaxation.",
        "pitch": "-16%",
        "rate": 0.80,
        "tags": ["sleep", "insomnia", "bedtime", "hypnotic", "relax"],
        "preview_text": "रात की ठंडी हवा आपके चेहरे को छू रही है... शरीर का हर एक अंग अब पूरी तरह से शांत और शिथिल हो रहा है...",
    },
    {
        "id": "hi-female-wellness-affirmations-77",
        "name": "Kalyani — Morning Gratitude & Affirmations",
        "gender": "female",
        "category": "Meditation",
        "style": "Serene & Uplifting",
        "description": "Luminous, gentle affirmations for self-love, morning gratitude, and emotional healing.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A serene female voice reciting positive Hindi affirmations with gentle warmth and uplifting light.",
        "pitch": "+0%",
        "rate": 0.86,
        "tags": ["affirmations", "gratitude", "healing", "wellness", "self love"],
        "preview_text": "मैं आज के इस नए दिन के लिए आभारी हूँ। मेरे भीतर असीम शांति, सकारात्मकता और शक्ति का वास है।",
    },
    {
        "id": "hi-male-spiritual-bhajan-intro-78",
        "name": "Pt. Hariprasad — Satsang & Vedic Reflection",
        "gender": "male",
        "category": "Meditation",
        "style": "Devotional & Reverent",
        "description": "Reverent, sacred tone for temple descriptions, Gita shlokas translation, and devotional intros.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A reverent male Vedic scholar speaking devotional Hindi with sacred peace and melodic cadence.",
        "pitch": "-8%",
        "rate": 0.88,
        "tags": ["spiritual", "vedic", "satsang", "gita", "bhajan"],
        "preview_text": "ईश्वर की सच्ची भक्ति किसी बाहरी आडंबर में नहीं, बल्कि मन की शुद्धि और सेवा भाव में निहित है।",
    },
    {
        "id": "hi-female-sound-healing-79",
        "name": "Divya — Chakra Balancing & Sound Healing",
        "gender": "female",
        "category": "Meditation",
        "style": "Ethereal & Soft",
        "description": "Whisper-soft, airy vocal timbre designed to accompany singing bowls and binaural meditation music.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "An ethereal soft female voice guiding chakra meditation in gentle, spacious Hindi.",
        "pitch": "-2%",
        "rate": 0.80,
        "tags": ["chakra", "sound healing", "ethereal", "soft", "wellness"],
        "preview_text": "अपने ध्यान को अनाहत चक्र पर केंद्रित करें... एक हरे रंग के प्रकाश को अपने हृदय में खिलता हुआ महसूस करें...",
    },
    {
        "id": "hi-male-zen-monk-80",
        "name": "Swami Bodhi — Zen Mindfulness",
        "gender": "male",
        "category": "Meditation",
        "style": "Minimalist & Centered",
        "description": "Still, centered delivery with deliberate long pauses for silent contemplation retreats.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A minimalist, deeply centered monk voice speaking concise philosophical Hindi with stillness.",
        "pitch": "-12%",
        "rate": 0.82,
        "tags": ["zen", "mindfulness", "monk", "stillness", "calm"],
        "preview_text": "विचारों को आने दीजिए, और जाने दीजिए। उनसे लड़िए मत... केवल एक शांत साक्षी बनकर उन्हें देखिए।",
    },
    {
        "id": "hi-female-sleep-nature-walk-81",
        "name": "Nirupama — Mountain & Forest Walk",
        "gender": "female",
        "category": "Meditation",
        "style": "Gentle & Dreamy",
        "description": "Dreamy imagery-rich narration describing dew-kissed pines, mountain streams, and twilight skies.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A dreamy female voice guiding an imaginary forest walk in Hindi for stress release.",
        "pitch": "-1%",
        "rate": 0.85,
        "tags": ["nature walk", "sleep", "dreamy", "imagery", "forest"],
        "preview_text": "आप एक सुंदर देवदार के जंगल से गुज़र रहे हैं। पैरों के नीचे सूखी पत्तियों की धीमी आवाज़ आ रही है...",
    },
    {
        "id": "hi-male-prayers-devotion-82",
        "name": "Mahant Ji — Temple Katha & Aarti",
        "gender": "male",
        "category": "Meditation",
        "style": "Solemn & Blessed",
        "description": "Solemn, pious narration for pilgrimage guides, temple histories, and festive holy rituals.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A pious Hindu temple priest narrating sacred stories in traditional, blessed Hindi.",
        "pitch": "-6%",
        "rate": 0.90,
        "tags": ["temple", "katha", "aarti", "holy", "devotion"],
        "preview_text": "हरिद्वार के पावन गंगा तट पर शाम की आरती के दीप जल उठे हैं और वातावरण में दिव्यता का संचार हो रहा है।",
    },

    # =========================================================================
    # 10. IVR, TELEPHONY & CUSTOMER SUPPORT (83-90)
    # =========================================================================
    {
        "id": "hi-female-ivr-banking-83",
        "name": "Sneha — Bank IVR & Phone Banking",
        "gender": "female",
        "category": "IVR & Support",
        "style": "Polite & Articulate",
        "description": "Crystal-clear, courteous telephony voice for account balance, OTP prompts, and card block menus.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A polite, articulate female bank telephony IVR automated voice speaking crisp Hindi with clear pacing.",
        "pitch": "+2%",
        "rate": 0.96,
        "tags": ["ivr", "banking", "phone", "telephony", "otp"],
        "preview_text": "हमारे बैंक में कॉल करने के लिए धन्यवाद। खाता शेष जानने के लिए 1 दबाएँ, नए कार्ड के आवेदन के लिए 2 दबाएँ।",
    },
    {
        "id": "hi-male-ivr-telecom-84",
        "name": "Rahul — Telecom Network Assistant",
        "gender": "male",
        "category": "IVR & Support",
        "style": "Clear & Helpful",
        "description": "Familiar telecom assistance voice for data recharge confirmations, roaming alerts, and bill queries.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A clear, helpful male telecom IVR automated voice speaking Hindi for mobile recharge and network balance.",
        "pitch": "+0%",
        "rate": 1.00,
        "tags": ["ivr", "telecom", "mobile", "recharge", "support"],
        "preview_text": "आपका वर्तमान डेटा पैक समाप्त होने वाला है। तुरंत 1.5 जीबी अतिरिक्त डेटा रिचार्ज करने के लिए 9 दबाएँ।",
    },
    {
        "id": "hi-female-ivr-flight-airline-85",
        "name": "Kavita — Airline Booking & Airport",
        "gender": "female",
        "category": "IVR & Support",
        "style": "Courteous & Welcoming",
        "description": "Pleasant, helpful customer support voice for flight re-scheduling, baggage queries, and web check-in.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A courteous airline customer support female voice answering passenger queries in refined Hindi.",
        "pitch": "+3%",
        "rate": 0.98,
        "tags": ["airline", "flight", "booking", "airport", "support"],
        "preview_text": "नमस्ते, एयरलाइन सहायता केंद्र में आपका स्वागत है। अपनी उड़ान की स्थिति जानने के लिए कृपया छह अंकों का पीएनआर दर्ज करें।",
    },
    {
        "id": "hi-male-ivr-delivery-courier-86",
        "name": "Mukesh — Delivery & Courier Bot",
        "gender": "male",
        "category": "IVR & Support",
        "style": "Direct & Conversational",
        "description": "Practical, direct voice for automated delivery OTP calls, package arrival updates, and address verification.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A direct and clear male automated delivery voice informing a customer about an incoming courier in Hindi.",
        "pitch": "+1%",
        "rate": 1.02,
        "tags": ["delivery", "courier", "otp", "package", "bot"],
        "preview_text": "नमस्ते! आपका पार्सल आज दोपहर 2 बजे तक पहुँच जाएगा। डिलीवरी बॉय को चार अंकों का ओटीपी अवश्य बताएँ।",
    },
    {
        "id": "hi-female-ivr-hospital-clinic-87",
        "name": "Dr. Anita — Hospital Appointment IVR",
        "gender": "female",
        "category": "IVR & Support",
        "style": "Calm & Empathetic",
        "description": "Empathetic, reassuring phone prompt for doctor booking, lab test reports, and clinic timings.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A reassuring and calm female voice assisting patients with hospital appointment scheduling in Hindi.",
        "pitch": "+0%",
        "rate": 0.94,
        "tags": ["hospital", "clinic", "doctor", "health", "ivr"],
        "preview_text": "स्वास्थ्य केंद्र में आपका स्वागत है। डॉक्टर से परामर्श का समय तय करने के लिए 1 दबाएँ, अपनी जाँच रिपोर्ट जानने के लिए 2 दबाएँ।",
    },
    {
        "id": "hi-male-ivr-government-helpline-88",
        "name": "Suresh — Citizen Helpline & Civic Bot",
        "gender": "male",
        "category": "IVR & Support",
        "style": "Formal & Patient",
        "description": "Patient, clear civic assistant voice for Aadhaar, electricity board grievances, and municipal alerts.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A patient, formal male voice on a public citizen grievance helpline speaking clear standard Hindi.",
        "pitch": "-2%",
        "rate": 0.95,
        "tags": ["civic", "helpline", "government", "aadhaar", "public"],
        "preview_text": "नागरिक सेवा पोर्टल पर आपका स्वागत है। बिजली बिल शिकायत दर्ज करने हेतु कृपया अपना उपभोक्ता नंबर दर्ज करें।",
    },
    {
        "id": "hi-female-ivr-hotel-concierge-89",
        "name": "Sunita — Hotel & Travel Concierge",
        "gender": "female",
        "category": "IVR & Support",
        "style": "Hospitable & Warm",
        "description": "Warm, hospitable service desk voice for room service orders, tour itineraries, and check-out requests.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A warm hospitable hotel concierge female speaking polite welcoming Hindi over the phone.",
        "pitch": "+4%",
        "rate": 0.96,
        "tags": ["hotel", "hospitality", "room service", "concierge"],
        "preview_text": "गुड इवनिंग! फ्रंट डेस्क पर आपकी क्या सेवा कर सकते हैं? कमरे में भोजन मंगाने के लिए कृपया अपना कमरा नंबर बताएँ।",
    },
    {
        "id": "hi-male-ivr-tech-support-90",
        "name": "Prateek — Broadband Tech Support Agent",
        "gender": "male",
        "category": "IVR & Support",
        "style": "Friendly & Problem-Solving",
        "description": "Friendly, tech-savvy phone agent guiding users through router reboots, Wi-Fi passwords, and speed tests.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A friendly male technical support agent explaining Wi-Fi troubleshooting steps in patient Hindi.",
        "pitch": "+2%",
        "rate": 1.00,
        "tags": ["tech support", "broadband", "wifi", "internet", "agent"],
        "preview_text": "कृपया अपने वाई-फ़ाई राउटर के पीछे लगे लाल बटन को दस सेकंड तक दबाकर रखें और फिर दोबारा चालू करें।",
    },

    # =========================================================================
    # 11. FORMAL ANNOUNCEMENTS & PUBLIC ADDRESS (91-95)
    # =========================================================================
    {
        "id": "hi-female-announcement-metro-91",
        "name": "Shubha — Metro Train Announcer",
        "gender": "female",
        "category": "Announcements",
        "style": "Formal & Iconic",
        "description": "Iconic, bell-clear public address voice for metro stations, next stop alerts, and safety warnings.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A crystal-clear iconic public announcement female voice on a metro train speaking formal Hindi.",
        "pitch": "+3%",
        "rate": 0.94,
        "tags": ["metro", "train", "announcement", "safety", "station"],
        "preview_text": "कृपया ध्यान दीजिए, अगला स्टेशन राजीव चौक है। दरवाज़े बाईं तरफ़ खुलेंगे। कृपया लाइन और ट्रेन के बीच की दूरी का ध्यान रखें।",
    },
    {
        "id": "hi-male-announcement-railway-92",
        "name": "Ramprasad — Indian Railways Station PA",
        "gender": "male",
        "category": "Announcements",
        "style": "Traditional & Reverberant",
        "description": "Nostalgic, loud railway platform announcer voice for train arrivals, departures, and platform changes.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A classic Indian Railways station platform male announcer speaking Hindi with resonant loudspeaker acoustics.",
        "pitch": "-4%",
        "rate": 0.92,
        "tags": ["railway", "irctc", "train", "platform", "loudspeaker"],
        "preview_text": "यात्रीगण कृपया ध्यान दें! गाड़ी संख्या 12424, नई दिल्ली से डिब्रूगढ़ जाने वाली राजधानी एक्सप्रेस प्लेटफ़ॉर्म नंबर 3 पर आ रही है।",
    },
    {
        "id": "hi-female-announcement-airport-gate-93",
        "name": "Meenakshi — Airport Departure Gate",
        "gender": "female",
        "category": "Announcements",
        "style": "Polite & International",
        "description": "Sophisticated, bilingual airport gate announcer for final boarding calls and gate updates.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A refined female airport gate announcer making final boarding announcements in clear Hindi.",
        "pitch": "+1%",
        "rate": 0.96,
        "tags": ["airport", "boarding", "gate", "flight", "terminal"],
        "preview_text": "यह मुंबई जाने वाली उड़ान संख्या 6E-204 के यात्रियों के लिए अंतिम बोर्डिंग सूचना है। कृपया तुरंत गेट नंबर 12 पर पहुँचें।",
    },
    {
        "id": "hi-male-announcement-civic-emergency-94",
        "name": "Ashok — Emergency & Disaster Siren Alert",
        "gender": "male",
        "category": "Announcements",
        "style": "Stern & Urgent",
        "description": "Stern, disciplined public safety announcement for cyclone alerts, flood warnings, and civil defense.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A stern male civil defense officer making emergency weather and flood alerts in authoritative Hindi.",
        "pitch": "-5%",
        "rate": 0.98,
        "tags": ["emergency", "siren", "disaster", "alert", "safety"],
        "preview_text": "सभी नागरिकों को सूचित किया जाता है कि भारी बारिश के कारण तटीय इलाक़ों से तुरंत सुरक्षित स्थानों की ओर प्रस्थान करें।",
    },
    {
        "id": "hi-female-announcement-shopping-mall-95",
        "name": "Tina — Shopping Mall & Event PA",
        "gender": "female",
        "category": "Announcements",
        "style": "Upbeat & Welcoming",
        "description": "Breezy, cheerful in-store announcer for mall promotions, lost-and-found, and food court highlights.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A cheerful, upbeat female voice making in-store shopping mall announcements in friendly Hindi.",
        "pitch": "+5%",
        "rate": 1.02,
        "tags": ["mall", "store", "shopping", "promotions", "events"],
        "preview_text": "मॉल में पधारे सभी ग्राहकों का हार्दिक अभिनंदन! आज तीसरे तल के फ़ूड कोर्ट में विशेष लाइव म्यूज़िक का आनंद लें।",
    },

    # =========================================================================
    # 12. SPECIALIZED CHARACTER & CREATIVE VOICES (96-100)
    # =========================================================================
    {
        "id": "hi-male-char-radio-detective-96",
        "name": "Inspector Byom — 1950s Radio Sleuth",
        "gender": "male",
        "category": "Storytelling",
        "style": "Vintage & Analytical",
        "description": "Old-school detective baritone with noir ambiance, crisp Hindi-Urdu vocabulary, and deliberate cadence.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A vintage 1950s Indian radio detective voice speaking slow dramatic Hindi-Urdu with noir mystery.",
        "pitch": "-12%",
        "rate": 0.88,
        "tags": ["detective", "noir", "vintage", "radio", "mystery"],
        "preview_text": "मुजरिम कितना भी चालाक क्यों न हो, एक छोटी सी भूल उसके पूरे खेल का पर्दाफ़ाश कर देती है जनाब।",
    },
    {
        "id": "hi-female-char-fairy-magic-97",
        "name": "Pari — Fairy Tale & Magical Guide",
        "gender": "female",
        "category": "Storytelling",
        "style": "Whimsical & Sparkly",
        "description": "Whimsical, high-sparkle fairy voice for fantasy bedtime adventures, talking animals, and children's apps.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A sparkly, whimsical fairy voice speaking gentle magical Hindi to young children.",
        "pitch": "+9%",
        "rate": 0.94,
        "tags": ["fairy", "magic", "kids", "bedtime", "fantasy"],
        "preview_text": "तारों के उस पार, परियों के जादुई देश में हर रात खुशियों के फूल खिलते हैं और चाँदनी गीत गाती है!",
    },
    {
        "id": "hi-male-char-cricket-commentator-98",
        "name": "Kapil — Live Cricket Radio Commentary",
        "gender": "male",
        "category": "YouTube & Social",
        "style": "Rapid-Fire & Electrifying",
        "description": "Electrifying, breathless Hindi commentary style capturing boundary hits, sixes, and stadium roar.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "An electrifying Hindi cricket commentator describing a six over long-on with peak excitement and fast delivery.",
        "pitch": "+6%",
        "rate": 1.15,
        "tags": ["cricket", "commentary", "sports", "stadium", "six"],
        "preview_text": "गेंदबाज़ दौड़े... हवा में उछली गेंद और ये लंबा शॉट! गेंद दर्शकों के बीच जाकर गिरी — शानदार गगनचुंबी छक्का!",
    },
    {
        "id": "hi-female-char-poet-shayari-99",
        "name": "Nazia — Shayari & Ghazal Reciter",
        "gender": "female",
        "category": "Storytelling",
        "style": "Soulful & Melodic",
        "description": "Soulful, melancholic voice for Urdu-Hindi poetry, ghazal recitals, and emotional couplets.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-SwaraNeural",
        "prompt": "A soulful female poet reciting Hindi-Urdu shayari with delicate pauses and heartfelt emotion.",
        "pitch": "-2%",
        "rate": 0.86,
        "tags": ["shayari", "poetry", "ghazal", "urdu", "soulful"],
        "preview_text": "ख़ामोशियों में भी एक अजब सी बात होती है, जब लफ़्ज़ कम पड़ जाएँ तो निगाहों से बात होती है...",
    },
    {
        "id": "hi-male-char-village-elder-100",
        "name": "Chaudhary Chacha — Village Wisdom",
        "gender": "male",
        "category": "Storytelling",
        "style": "Rustic & Warm",
        "description": "Warm, earthy elder voice rich in village folklore, desi proverbs, and grassroots common sense.",
        "engine": "indic-parler",
        "base_speaker": "hi-IN-MadhurNeural",
        "prompt": "A warm rustic Indian village elder speaking desi Hindi with rich storytelling humor and folk wisdom.",
        "pitch": "-8%",
        "rate": 0.90,
        "tags": ["village", "desi", "folk", "wisdom", "elder"],
        "preview_text": "अरे भैया, सीधी सी बात है — जो बीज आज ज़मीन में बोओगे, कल उसी का फल पाओगे। इसमें कोई दो राय नहीं!",
    },
]

# Quick indexing by ID
HINDI_VOICES_BY_ID: dict[str, HindiVoiceProfile] = {v["id"]: v for v in HINDI_VOICES}


def get_hindi_voice(voice_id: str) -> HindiVoiceProfile | None:
    return HINDI_VOICES_BY_ID.get(voice_id)


def list_hindi_voices() -> list[HindiVoiceProfile]:
    return list(HINDI_VOICES)
