"""
POST /api/tts — Fish Audio Text-to-Speech endpoint.

Returns raw MP3 audio generated by Fish Audio using a pre-cloned voice.
Requires FISH_API_KEY, FISH_VOICE_ID, and FISH_TTS_MODEL in .env.

TODO: Add auth/session check before deploying to production.
      All other routes in this project are also unauthenticated (see routes_voices.py,
      routes_generations.py). This will be handled in a separate auth task.
"""
import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
from pydantic import BaseModel, Field

from app.config import settings
from app.messages import (
    FISH_TTS_INVALID_VOICE_KEY,
    FISH_TTS_TEXT_EMPTY,
    FISH_TTS_TEXT_TOO_LONG,
    FISH_TTS_TIMEOUT,
    FISH_TTS_UPSTREAM_ERROR,
)
from app.services.fish_tts import FishTTSError, FishTTSTimeoutError, generate_speech

logger = logging.getLogger(__name__)
router = APIRouter(tags=["tts"])


class TTSRequest(BaseModel):
    text: str = Field(min_length=1)
    voice: str | None = None


@router.post("/api/tts")
async def tts(body: TTSRequest) -> Response:
    text = body.text.strip()

    if not text:
        raise HTTPException(400, FISH_TTS_TEXT_EMPTY)

    if len(text) > settings.TTS_MAX_TEXT_LENGTH:
        raise HTTPException(400, FISH_TTS_TEXT_TOO_LONG)

    if body.voice is not None and body.voice not in settings.TTS_VOICE_KEYS:
        raise HTTPException(
            400,
            FISH_TTS_INVALID_VOICE_KEY.format(valid_keys=", ".join(settings.TTS_VOICE_KEYS)),
        )

    try:
        audio_bytes = await generate_speech(text, body.voice)
    except EnvironmentError as exc:
        # Misconfigured server or voice — log full message, return generic error without leaking secrets.
        logger.error("Fish TTS env misconfigured: %s", exc)
        raise HTTPException(500, str(exc)) from exc
    except FishTTSTimeoutError:
        raise HTTPException(504, FISH_TTS_TIMEOUT)
    except FishTTSError:
        raise HTTPException(502, FISH_TTS_UPSTREAM_ERROR)
    except Exception as exc:  # noqa: BLE001
        logger.exception("Fish TTS unexpected error")
        raise HTTPException(500, FISH_TTS_UPSTREAM_ERROR) from exc

    return Response(content=audio_bytes, media_type="audio/mpeg")
